######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 26 20:18:46 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lopenal -lvorbisfile

# Input
HEADERS += manager.h openal_helper.h
SOURCES += manager.cpp openal_helper.cpp
